package com.ventura.apptest.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ventura.apptest.data.User;
import com.ventura.apptest.data.Places;

import com.ventura.apptest.data.UserDao;
import com.ventura.apptest.data.PlacesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig placesDaoConfig;

    private final UserDao userDao;
    private final PlacesDao placesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        placesDaoConfig = daoConfigMap.get(PlacesDao.class).clone();
        placesDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        placesDao = new PlacesDao(placesDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Places.class, placesDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        placesDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PlacesDao getPlacesDao() {
        return placesDao;
    }

}
